# Generated by Django 3.1.5 on 2021-06-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
